#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running tests..."
npm test || exit 1

echo "Running ESLint..."
npm run lint || exit 1

echo "Checking Prettier formatting..."
npm run format:check || exit 1
